deadList={
"Alien": [
"Ellen Ripley",
],
"A Nightmare on Elm Street": [
"Nancy Thompson",
"Donald Thompson",
"Kristen Parker",
"Roland Kincaid",
"Joey Krusel",
"Dan Jordan",
],
"Ant Man": [
"Ant",
"Hope Van Dyne/ Wasp",
"Dr Hank Pym",
"Janet Van Dyne",
],
"Armageddon": [
"Harry Stamper",
],
"Arrow": [
"Tommy Merlyn",
"Moira Queen",
"Oliver Queen/Green Arrow",
"John Diggle/Spartan",
"Felicity Smoak/Overwatch",
"Laurel Lance/Black Canary",
"Thea Queen/Speedy",
"Laurel Lance/Black Canary",
"Malcolm Merlyn/Dark Archer",
"Quentin Lance",
"Roy Harper/Arsenal",
"Emiko Adachi",
],
"Avatar": [
"Eytukan",
"Dr Grace Augustine",
"Tsu'Tey",
"Trudy Chacon",
],
"Avengers": [
"Agent Phil Coulson",
"Pietro Maximoff/ Quicksilver",
"Gamora",
"Everyone who died when Thanos destroyed half the universe: Revived by the Hulk",
"Vision",
"Natasha Romanoff/ Black Widow",
"Tony Stark/ Iron Man",
],
"Batman": [
"Thomas Wayne",
"Martha Wayne",
"Selina Kyle",
],
"Bohemian Rhapsody": [
"Freddie Mercury",
],
"Bourne": [
"Marie Helena Kreutz",
"Simon Ross",
"Nicky Parsons",
],
"Buffy the Vampire Slayer": [
"Buffy Summers",
"Buffy Summers",
],
"Captain America": [
"Dr Abraham Erskine",
"Colonel Chester Phillips",
"Agent Peggy Carter",
],
"Captain Marvel": [
"Dr Wendy Lawson/ Mar Vell",
"Norex",
"Goose the Flerken",
],
"Charmed": [
"Prue Halliwell",
],
"The Dark Knight": [
"Thomas Wayne",
"Martha Wayne",
"Rachel Dawes",
"Mayor Anthony Garcia",
],
"The DC Extended Universe": [
"Jor El",
"Jonathan Kent",
"Jason Todd/ Red Hood",
"Senator Wallace Keefe",
"Senator June Finch",
"Kal El/ Clark Kent/ Superman",
"Chato Santana/ El Diablo",
"Antiope",
"Captain Steve Trevor",
"The Wizard Shazam",
],
"Dead Zone": [
"Johnny Smith",
],
"Death Note": [
"Light Yagami",
],
"Disney Princess Movies": [
"Aurora",
"The Beast",
"Ray",
"Flynn Rider",
"Anna",
"Gramma Tala",
"Elsa",
"Olaf",
],
"Doctor Strange": [
"Stephen Strange/Doctor Strange",
"The Ancient One",
"Wong",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
"Stephen Strange/Doctor Strange",
],
"Donnie Darko": [
"Donnie Darko",
],
"Dragonball Z": [
"Goku",
"Goku",
],
"Epic Movie": [
"Peter, Susan, Edward, and Lucy",
],
"Fantastic Beasts": [
"Leta Lestrange",
],
"Fast and Furious": [
"Gisele Yashar",
"Han Seoul Oh",
"Elena Neves",
],
"Final Destination": [
"Carter Daniels",
"Alex Browning",
"Clear Rivers",
"Wendy Christensen",
"Kevin Fischer",
"Julie Christensen",
"Nick O'Bannon",
"Lori Milligan",
"Janet Cunningham",
"Sam Lawton",
"Molly Harper",
"Nathan Sears",
],
"Friday the 13th": [
"Alice Hardy",
"Crazy Ralph",
],
"Friends": [
"Frances Buffay",
"The Chick and the Duck",
"Estelle Leonard",
],
"Game of Thrones": [
"King Robert Baratheon",
"Lord Ned \"Eddard\" Stark",
"King Robb Stark",
"Lady Catelyn Stark",
"Lord Commander Jon Snow",
"Queen Margaery Tyrell",
"Jamie Lannister",
"Daenerys Targaryen",
],
"Gladiator": [
"Maximus",
],
"The Godfather": [
"Sonny Corleone",
"Don Vito Corleone",
"Michael Corleone",
],
"God of War": [
"Kratos",
],
"Guardians of the Galaxy": [
"Meredith Quill",
"Garthaan Saal",
"Horuz",
"Groot",
"Yondu Udonta",
],
"Halloween": [
"Laurie Strode",
"Dr. Samuel Loomis",
"Marion Chambers",
"Jamie Lloyd",
"Rachel Carruthers",
"Sheriff Ben Meeker",
"Deputy Frank Hawkins",
],
"Hamlet": [
"Hamlet",
],
"Harry Potter": [
"James Potter",
"Lily Potter",
"Cedric Diggory",
"Sirius Black",
"Albus Dumbledore",
"Hedwig",
"Alastor \"Mad Eye\" Moody",
"Dobby",
"Severus Snape",
"Fred Weasley",
"Collin Creevey",
"Remus Lupin",
"Nymphadora Tonks",
],
"The Hobbit": [
"King Thror",
"King Thrain",
"Fili",
"Kili",
"Thorin Oakenshield",
],
"The Hunger Games": [
"Rue",
"Cinna",
"Mags",
"Boggs",
],
"Indiana Jones": [
"Wu Han",
"Kazim",
"Grail Knight",
"Dr. Henry Jones",
"Dr. Marcus Brody",
"George \"Mac\" McHale",
],
"Iron Man": [
"Dr Ho Yinsen",
"Maya Hansen",
],
"It": [
"Georgie Denbrough",
"Stanley Uris",
"Dean",
"Eddie Kaspbrak",
],
"James Bond": [
"Quarrel",
"Ali Kerim Bey",
"Jill Masterson",
"Tilly Masterson",
"Count Lippe",
"Aki",
"Tracy Bond",
"Plenty O'Toole",
"Rosie Carver",
"Andrea Anders",
"Commander Talbot",
"James Hunt",
"Corinne Dufour",
"Jaws",
"Dolly",
"Countess Lisl von Shaft",
"Agent 009",
"Sir Godfrey Tibbett",
"Chuck Lee",
"Pan Ho",
"Jenny Flex",
"Saunders",
"Felix Leiter",
"Sharkey",
"Paris Carver",
"Valentin Zukovsky",
"Solange Dimitrios",
"Vesper Lynd",
"Rene Mathias",
"Severine",
"M",
],
"Judy": [
"Judy Garland",
],
"Jurassic Park": [
"John \"Ray” Arnold",
"Robert Muldoon",
"Eddie Carr",
"Ajay Sidhu",
"Ben Hildebrand",
"Udesky",
"Supervisor Nick",
"Simon Masrani",
"Zara Young",
"Charlie (Velociraptor)",
"Delta (Velociraptor)",
"Echo (Velociraptor)",
"Sir Benjamin Lockwood",
],
"Kingsman": [
"Harry Hart",
"Merlin",
],
"Kung Fu Panda": [
"Master Oogway",
"Mantis",
"Crane",
"Monkey",
"Viper",
"Master Shi Fu",
],
"Legends of Tomorrow": [
"Leonard Snart/Captain Cold",
"Ray Palmer/Atom",
"Jefferson Jackson/Firestorm",
"Mick Rory/Heat Wave",
"Nate Heywood/Steel",
"Rip Hunter",
"Sara Lance/White Canary",
"Dr Martin Stein",
"Rip Hunter",
],
"Leon: The Professional": [
"Leon",
],
"Les Miserables": [
"Fantine",
"Eponine",
"Gavroche",
"Enjolras",
"Jean Valjean",
],
"Lord of the Rings": [
"Boromir",
"Gandalf the Grey",
"King Theoden",
],
"Macbeth": [
"Macbeth",
],
"Maricraft: Block of Love: No one really dies they just lose": [
"Max Realname",
"Unknown Guy",
"Jovenshire",
"Craig",
"Jovenshire: Lost the challenge: Came back in the challenge",
],
"Maricraft: Hero House: No one really died just lost the challenge": [
"Craig/ Ninjew",
"Max Realname/ Max Realhero",
"Courtney/ Fire Crotchney",
"Unknown Guy/ The Incredible Mr $##@#^!@#$&&%$",
"Boze/ Invisihoe",
"Sage/ Sailor Sage",
"Joven/ Bat",
],
"Maricraft: Outlaster": [
"Flitzypoo",
"TheJovenshire",
"AtomicUnderpants",
"Lazercorn",
"Real_Sohinki",
],
"Minecraft: Friday the 13th": [
"Mario",
],
"Mario": [
"Mario",
],
"Marvel Cinematic Universe": [
"Bruce Banner/Hulk",
"Thor Odinson",
"Bruce Banner/Hulk",
],
"The Matrix": [
"Dozer: Electrocuted by Cypher using lightning rifle",
"Apoc: Disconnected from Matrix when Cypher retrieves the stuff from the back of his neck, killing him",
"Switch: Disconnected from Matrix when Cypher retrieves the stuff from the back of her neck, killing her",
"Neo: Shot by Smith in the Matrix. He comes back to life when Trinity kisses him",
"Tank",
"Trinity",
"The Oracle",
"Trinity",
"Neo",
],
"Men in Black": [
"Agent Kay",
],
"Mission Impossible": [
"Lindsey Farris",
"Leonid Lisenker",
"Alan Hunley",
],
"My Little Pony: Friendship is Magic": [
"Twilight Sparkle",
],
"Oblivion": [
"Jack Harper",
],
"Pacific Rim": [
"Chuck Hanson",
"Stacker Pentecost",
"Mako Mori",
"Suresh Khuran",
],
"Phantom of the Paradise": [
"Winslow Leach",
],
"Pinocchio": [
"Pinocchio",
],
"Pirates of the Caribbean": [
"Captain Jack Sparrow",
"Governor Weatherby Swann",
"James Norrington",
"William Turner II",
"Hector Barbossa",
],
"Pixar Flims": [
"Mike Wazowski",
"Gazerbeam",
"Wall E",
"Doc Hudson",
"Bing Bong",
"Henry",
"Hector",
"Mama Coco",
],
"Planet of the Apes": [
"Nova",
"John Brent",
"George Taylor",
"Dr. Zira",
"Dr. Cornelius",
"Caesar",
],
"Pulp Fiction": [
"Vincent Vega",
],
"Romeo and Juliet": [
"Romeo",
"Juliet",
],
"Saw": [
"Adam Stanheight",
"Detective Eric Matthews",
"Jeff Reinhart",
"Lt. Daniel Rigg",
"Special Agent Peter Strahm",
"William Easton",
],
"Scary Movie": [
"Cindy Campbell",
"Brenda Meeks",
],
"Sin City": [
"Marv",
"John Hartigan",
],
"Sonic the Hedgehog": [
"Sonic the Hedgehog",
],
"Spartacus": [
"Spartacus",
],
"Spider Man": [
"Benjamin \"Ben\" Parker",
"Harry Osborn",
"Dr. Otto Octavius",
"Benjamin \"Ben\" Parker",
"Captain George Stacy",
"Gwen Stacy",
"Aaron Davis/ Prowler",
"SP//DR Suit",
"Steve Rogers/ Captain America",
],
"Star Trek": [
"Captain Kirk",
],
"Star Trek Reboot": [
"George Kirk",
"Captain Pike",
"Captain Kirk",
],
"Star Wars: Rebels ": [
"Maketh Tua",
"Jun Sato",
"Caleb Dume/ Kanan Jarrus",
"Captain Gregor",
],
"Stranger Things": [
"Barbara Holland",
"Bob Newby",
"Dr Alexei",
"Billy Hargrove",
"Chief Jim Hopper",
],
"Supernatural": [
"Dean Winchester",
"Sam Winchester",
],
"The Flash": [
"Nora Allen",
"Eddie Thawne",
"Ronnie Raymond/Firestorm",
"Henry Allen",
"H.R Wells",
"Nora West Allen/XS",
],
"The Good Place": [
"Eleanor Shellstrop",
"Chidi Anagonye",
"Tahani Al Jamil",
"Jason Mendoza",
"Janet",
"Eleanor Shellstrop",
"Chidi Anagonye",
"Tahani Al Jamil",
"Jason Mendoza",
"John Wheaton",
"Simone Garnett",
"Brent Norwalk",
"Derek",
"Derek",
"Derek",
],
"The Terminator": [
"Kyle Reese",
"Miles Dyson",
"T800/ The Terminator",
"Sarah Connor",
"T850/ Model 101",
"Diego Ramos",
"Grace",
"Carl/ T800",
],
"The Texas Chainsaw Massacre": [
"Lt. Lefty Enright",
],
"The Walking Dead": [
"Dale Horvath",
"Lori Grimes",
"Merle Dixon",
"Andrea",
"Hershel Greene",
"Bob Stookey",
"Beth Greene",
"Tyreese Williams",
"Jessie Anderson",
"Abraham Ford",
"Glenn Rhee",
"Sasha Williams",
"Carl Grimes",
"Paul \"Jesus\" Rovia",
"Tara Chambler",
"Enid",
],
"Thor": [
"Thor Odinson",
"Queen Frigga",
"Odin Allfather",
"Volstagg",
"Fandral",
"Hogun",
],
"Timeline": [
"Andre Marek",
],
"Transformers": [
"Optimus Prime",
"Sam Whitwicky",
"Jetfire",
"Wheeljack",
"Lucas Flannery",
"Sir Edmund Burton",
"Agent Powell",
],
"Watchmen": [
"The Comedian",
"Rorschach",
],
"West Side Story": [
"Tony Wyzek",
"Riff Lorton",
],
"X-Men": [
"John Wraith",
"Kayla Silverfox",
"Senator Robert Kelly",
"Scott Summers/ Cyclops",
"Charles Xavier/ Professor X",
"Harada",
"Alex Summers/ Havok",
"Raven Darkholme/ Mystique",
"Jean Grey/ Dark Phoenix",
"Vanessa",
"Jesse Aaronson/ Bedlam",
"Rusty/ Shatterstar",
"Peter W",
"Axel Cluney/ Zeitgeist",
"Charles Xavier/ Professor X",
"Logan Howlett/ Wolverine",
],
"Xtro": [
"Rachel Phillips",
],
"Zelda": [
"Link",
],
"I Know What You Did Last Summer": [
"Julie James",
"Ray Bronson",
"Amber Williams",
],
"White: The Melody of Curse": [
"Ali Abdul/Player 199",
"Jang Deok",
"Han Mi",
"Hwang Jung",
"Kang Sae",
"Cho Sang",
"Oh Il",
],
"Vincenzo": [
"Ali Abdul/Player 199",
"Jang Deok",
"Han Mi",
"Hwang Jung",
"Kang Sae",
"Cho Sang",
"Oh Il",
],
"Squid Game": [
"Ali Abdul/Player 199",
"Jang Deok",
"Han Mi",
"Hwang Jung",
"Kang Sae",
"Cho Sang",
"Oh Il",
],
}
